schemaVersion: 2.1.0
metadata:
  name: voting-app-py-ds
attributes:
  controller.devfile.io/storage-type: ephemeral
components:
- name: devtools
  container:
    image: quay.io/mloriedo/universal-developer-image:ubi8-latest
    memoryLimit: 2G
    memoryRequest: 256Mi
    cpuLimit: 500m
    cpuRequest: 30m
commands:
  - exec:
      commandLine: python -m venv .venv && . .venv/bin/activate && python app.py
      component: python
      group:
        kind: run
      label: Run the application
      workingDir: '${PROJECTS_ROOT}/voting-app-py-ds'
    id: run