schemaVersion: 2.1.0
metadata:
  name: voting-app-py-ds   
components:
  - name: python
    container:
      image: registry.redhat.io/devspaces/udi-rhel8:3.0
      env:
        - name: REDIS_HOST
          value: new-redis.pdf-voting-app-demo.svc.cluster.local
        - name: REDIS_PASSWORD
          value: admin
