schemaVersion: 2.1.0
metadata:
  name: voting-app-py-ds   
components:
  - name: python
    container:
      image: registry.redhat.io/devspaces/udi-rhel8:3.0
commands:
  - id: run
    exec:
      label: "Run the application"
      component: python
      workingDir: ${PROJECTS_ROOT}/voting-app-py-ds
      commandLine: python -m venv .venv && . .venv/bin/activate && python app.py
      group:
        kind: run
