schemaVersion: 2.1.0
metadata:
  name: voting-app-py-ds
components:
  - name: checode
    volume: {}
  - name: che-code-injector
    container:
      image: quay.io/che-incubator/che-code:insiders-694ef6e
      command:
        - /entrypoint-init-container.sh
      cpuLimit: 500m
      cpuRequest: 30m
      memoryLimit: 128Mi
      memoryRequest: 32Mi
      volumeMounts:
        - name: checode
          path: /checode
  - name: python
    container:
      image: 'registry.redhat.io/devspaces/udi-rhel8:3.0'
      command:
        - /checode/entrypoint-volume.sh
      cpuLimit: 500m
      cpuRequest: 30m
      memoryLimit: 1024Mi
      memoryRequest: 256Mi
      env:
        - name: REDIS_HOST
          value: new-redis.pdf-voting-app-demo.svc.cluster.local
        - name: REDIS_PASSWORD
          value: admin
      sourceMapping: /projects
      volumeMounts:
        - name: checode
          path: /checode
